name: Build, Publish, and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ACR_NAME: wgacr01
  WEBAPP_NAME: webappwg0101

jobs:
  build-publish-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Azure Container Registry Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
    
    - name: Build and push Docker image
      working-directory: ./basicfront
      run: |
        docker build -t ${{ env.ACR_NAME }}.azurecr.io/basicfront:${{ github.sha }} .
        docker push ${{ env.ACR_NAME }}.azurecr.io/basicfront:${{ github.sha }}
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        images: ${{ env.ACR_NAME }}.azurecr.io/basicfront:${{ github.sha }}
